////
- Copyright (c) 2023-2024, Thomas Atkinson
-
- SPDX-License-Identifier: Apache-2.0
-
- Licensed under the Apache License, Version 2.0 the "License";
- you may not use this file except in compliance with the License.
- You may obtain a copy of the License at
-
-     http://www.apache.org/licenses/LICENSE-2.0
-
- Unless required by applicable law or agreed to in writing, software
- distributed under the License is distributed on an "AS IS" BASIS,
- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
- See the License for the specific language governing permissions and
- limitations under the License.
-
////
= File System

In computing, a file system is responsible for storing, organizing, and retrieving data from a storage medium like a hard drive, SSD, or network storage. Different operating systems and environments often have different file systems with their own characteristics and limitations.

In Vulkan Samples we support a range of platforms. Luckily, there are only a couple types of filesystems that we must support and each filesystem is supported by the C++ standard library. The filesystems we support are:

* Windows
* Linux
* Android
* macOS

There are only a few differences where the standard library does not support the filesystem features we require. However, https://en.cppreference.com/w/cpp/filesystem[std::filesystem,window=_blank] (since C++17) works for our usecases.

== Why implement a filesystem interface?

It is important to make sure that your project can adapt to new requirements without the need to refactor large amounts of code. A filesystem interface allows you to easily swap out the filesystem implementation for a different one. For example, you may want to use a different filesystem implementation for testing or for a different platform.

In the future we may want to implement a network filesystem to stream assets from a server. We may also want to implement a filesystem that can read from a zip file. We can do this without changing any of the code that uses the filesystem interface.
