repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v15.0.7'
    hooks:
    -   id: clang-format
        'types_or': [c++, c]
-   repo: local
    hooks:
    -   id: copyright-check
        name: copyright-check
        entry: ./scripts/copyright.py main --fix
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
