version: '{build}'

branches:
  only:
    - master

image:
  - Visual Studio 2017
  - Ubuntu

platform:
- x64

configuration:
  - Release
  - Debug

for:
  -
    matrix:
      only:
        - configuration: Release
    build_script:
      - cmd: cmake -Bbuild -H"."
      - cmd: cmake --build build --config Debug --target vulkan_samples
  -
    matrix:
      only:
        - configuration: Debug
    build_script:
      - cmd: cmake -Bbuild -H"."
      - cmd: cmake --build build --config Debug --target vulkan_samples

