////
- Copyright (c) 2024, Holochip Corporation
-
- SPDX-License-Identifier: Apache-2.0
-
- Licensed under the Apache License, Version 2.0 the "License";
- you may not use this file except in compliance with the License.
- You may obtain a copy of the License at
-
-     http://www.apache.org/licenses/LICENSE-2.0
-
- Unless required by applicable law or agreed to in writing, software
- distributed under the License is distributed on an "AS IS" BASIS,
- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
- See the License for the specific language governing permissions and
- limitations under the License.
-
////

= Mesh shading

ifdef::site-gen-antora[]
TIP: The source for this sample can be found in the https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/hpp_mesh_shading[Khronos Vulkan samples github repository].
endif::[]

:pp: {plus}{plus}

NOTE: This is a transcoded version of the extension sample https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/mesh_shading[Mesh Shading] that illustrates the usage of the C{pp} bindings of vulkan provided by Vulkan-Hpp.

This code sample demonstrates how to create the absolute most basic mesh shading example.
It creates a single  triangle in a mesh shader.
There is no vertex shader, there is only a mesh shader and a fragment shader.
