////
Copyright (c) 2026, Sascha Willems

 SPDX-License-Identifier: Apache-2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////
= Descriptor heap

ifdef::site-gen-antora[]
TIP: The source for this sample can be found in the https://github.com/KhronosGroup/Vulkan-Samples/tree/main/samples/extensions/descriptor_heap[Khronos Vulkan samples github repository].
endif::[]

== Overview

Managing descriptors is one of the harder parts of Vulkan. The link:https://docs.vulkan.org/features/latest/features/proposals/VK_EXT_descriptor_buffer.html[VK_EXT_descriptor_buffer] extension aimed to simplify this, but it came with a few caveats.

The link:https://docs.vulkan.org/features/latest/features/proposals/VK_EXT_descriptor_heap.html[VK_EXT_descriptor_heap] extension addresses these caveats and completely overhauls Vulkan's descriptor system by providing direct access to descriptor memory using heaps, while still preserving compatibility with shaders that use legacy descriptor sets (optionally) or, more forward-looking, untyped pointers.

This extension is intended to completely replace Vulkan's existing descriptor set mechanism and, if available, supersedes descriptor buffers. It is meant to be the way forward for passing data to shaders.

Instead of having to create and bind individual descriptors, descriptor information is stored in heaps, which are just buffers. Descriptors effectively become memory. This also no longer requires the use of descriptor layouts.

To sum it up: descriptor heaps greatly simplify descriptor management and make it much more flexible.

== Heap types

Implementations require two distinct heap types, so this extension differentiates between:

- Sampler heaps for storing samplers
- Resource heaps for storing all other resource types like buffers and images

So in a typical scenario where we want to use e.g. uniform buffers, storage buffers, images and samplers, we need to create two distinct heaps.

== Creating heaps

As noted above, heaps are basically just memory that you can copy descriptor-related information to. Creating a heap therefore is no different from creating any other buffer in Vulkan and requires the `VK_BUFFER_USAGE_DESCRIPTOR_HEAP_BIT_EXT` usage flag:

[,cpp]
----
const VkDeviceSize heap_buffer_size = aligned_size(2048 + descriptor_heap_properties.minResourceHeapReservedRange, descriptor_heap_properties.resourceHeapAlignment);

descriptor_heap_resources =
    std::make_unique<vkb::core::BufferC>(
        get_device(),
        heap_buffer_size,
        VK_BUFFER_USAGE_DESCRIPTOR_HEAP_BIT_EXT |  VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,
        VMA_MEMORY_USAGE_CPU_TO_GPU);
----

== Uploading data to heaps

What information is required to store a descriptor type in a heap varies. The destination where this information is stored in the heap is passed using link:https://docs.vulkan.org/refpages/latest/refpages/source/VkHostAddressRangeEXT.html[host address ranges].

For samplers, we pass `VkSamplerCreateInfo` (no need to create an actual `VkSampler`):

[,cpp]
----
VkSamplerCreateInfo sampler_ci{
    .sType = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
	.magFilter     = VK_FILTER_LINEAR,
	.minFilter     = VK_FILTER_LINEAR,    
    ...};
VkHostAddressRangeEXT sampler_har{
    .address = (uint8_t *) (descriptor_heap_samplers->get_data()) + sampler_heap_offset,
	.size    = sampler_descriptor_size};
vkWriteSamplerDescriptorsEXT(get_device().get_handle(), 1, &sampler_ci, &sampler_har);
----

For images, we pass `VkImageViewCreateInfo` (pointing to the actual `VkImage`):

[,cpp]
----
VkImageViewCreateInfo image_view_ci{
    .sType            = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
    .image            = texture.image->get_vk_image().get_handle(),
    .viewType         = VK_IMAGE_VIEW_TYPE_2D
    ...};
VkImageDescriptorInfoEXT image_descriptor_info{
    .sType  = VK_STRUCTURE_TYPE_IMAGE_DESCRIPTOR_INFO_EXT,
    .pView  = &image_view_ci,
    ...};
VkResourceDescriptorInfoEXT image_resource_desc{
    .sType = VK_STRUCTURE_TYPE_RESOURCE_DESCRIPTOR_INFO_EXT,
    .type  = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
    .data  = {.pImage = &image_descriptor_info}};
VkHostAddressRangeEXT       image_host_address{
    .address = (uint8_t *) (descriptor_heap_resources->get_data()) + image_heap_offset,
    .size    = image_descriptor_size};
vkWriteResourceDescriptorsEXT(get_device().get_handle(), 1, &image_resource_desc, &image_host_address);
----

For buffers, we just pass their device address and range:

[,cpp]
----
VkDeviceAddressRangeEXT buffer_device_addr_range{
    .address = uniform_buffer->get_device_address(),
    .size = uniform_buffer->get_size()};
VkResourceDescriptorInfoEXT buffer_resource_desc{
    .sType = VK_STRUCTURE_TYPE_RESOURCE_DESCRIPTOR_INFO_EXT,
    .type  = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
    .data  = {.pAddressRange = &buffer_device_addr_range}};
VkHostAddressRangeEXT buffer_host_address{
    .address = (uint8_t *) (descriptor_heap_resources->get_data()),
    .size    = buffer_descriptor_size};
vkWriteResourceDescriptorsEXT(get_device().get_handle(), 1, &buffer_resource_desc, &buffer_host_address);
----

link:https://docs.vulkan.org/refpages/latest/refpages/source/vkWriteResourceDescriptorsEXT.html[vkWriteResourceDescriptorsEXT] and link:https://docs.vulkan.org/refpages/latest/refpages/source/vkWriteSamplerDescriptorsEXT.html[vkWriteSamplerDescriptorsEXT] are then used to write the descriptors to heap memory.

**Note:** The above examples are simplified to show a basic setup. The `vkWrite*DescriptorsEXT` functions can be used to write multiple descriptors to a heap at once.

== Binding heaps

Heaps are bound per heap type using link:https://docs.vulkan.org/refpages/latest/refpages/source/vkCmdBindResourceHeapEXT.html[vkCmdBindResourceHeapEXT], so if you use a resource heap and a sampler heap, you need to issue two binding calls:

[,cpp]
----
// Bind the resource heap (buffers and images)
VkBindHeapInfoEXT bind_heap_info_res{
    .sType = VK_STRUCTURE_TYPE_BIND_HEAP_INFO_EXT,
    .heapRange{
        .address = descriptor_heap_resources->get_device_address(),
        .size    = descriptor_heap_resources->get_size()},
    .reservedRangeOffset = descriptor_heap_resources->get_size() - descriptor_heap_properties.minResourceHeapReservedRange,
    .reservedRangeSize = descriptor_heap_properties.minResourceHeapReservedRange,
};
vkCmdBindResourceHeapEXT(draw_cmd_buffer, &bind_heap_info_res);

// Bind the sampler heap
VkBindHeapInfoEXT bind_heap_info_samplers{
    .sType = VK_STRUCTURE_TYPE_BIND_HEAP_INFO_EXT,
    .heapRange{
        .address = descriptor_heap_samplers->get_device_address(),
        .size    = descriptor_heap_samplers->get_size()},
    .reservedRangeOffset = descriptor_heap_samplers->get_size() - descriptor_heap_properties.minSamplerHeapReservedRange,
    .reservedRangeSize = descriptor_heap_properties.minSamplerHeapReservedRange};
vkCmdBindSamplerHeapEXT(draw_cmd_buffer, &bind_heap_info_samplers);

...

// All draw calls will source from heaps (until non-heap bindings are issued)
vkCmdDrawIndexed(draw_cmd_buffer, cube->vertex_indices, 2, 0, 0, 0);
----

**Note:** One important difference, compared to other buffers, is the **reserved range** (e.g. `reservedRangeOffset` and `reservedRangeSize`). Implementations, to varying degrees, need additional space for some descriptor-related operations. This space must not be used by the application, so we need to both allocate it and mark those regions as reserved. For this sample, we put the reserved range after the space where we have copied the descriptors.

== Push data (instead of push constants)

This extension also adds a more direct way to push state data to the command buffer. With no need for pipeline layouts, this is now much simpler and is done via a single call to link:https://docs.vulkan.org/refpages/latest/refpages/source/vkCmdPushDataEXT.html[vkCmdPushDataEXT]:

[,cpp]
----
PushData push_data{ ... };
VkPushDataInfoEXT push_data_info{
    .sType = VK_STRUCTURE_TYPE_PUSH_DATA_INFO_EXT,
    .data  = {.address = &push_data, .size = sizeof(PushData)}};
vkCmdPushDataEXT(draw_cmd_buffer, &push_data_info);
----

== Accessing heaps

The extension lets us access descriptors in shaders in two different ways:

=== Descriptor set and binding mappings

link:https://docs.vulkan.org/refpages/latest/refpages/source/VkDescriptorSetAndBindingMappingEXT.html[VkDescriptorSetAndBindingMappingEXT] can be used to simplify porting existing codebases to descriptor heaps. By using this, existing shaders can be used without having to modify them. The syntax for binding descriptors, regardless of shading language, stays the same.

[,glsl]
----
// Vertex shader
layout (set = 0, binding = 0) uniform UBO {
	mat4 projection;
	mat4 view;
	mat4 model;
} ubo[2];

// Fragment shader
layout (set = 1, binding = 0) uniform texture2D textureImage[2];
layout (set = 2, binding = 0) uniform sampler textureSampler[2];
----

The app then defines how the heaps are mapped to those bindings:

[,cpp]
----
std::array<VkDescriptorSetAndBindingMappingEXT, 3> set_binding_mappings{};

// Maps "layout (set = 0, binding = 0) uniform UBO"
set_binding_mappings[0] = {
    .sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_AND_BINDING_MAPPING_EXT,
    .descriptorSet = 0,
    .firstBinding  = 0,
    .bindingCount  = 1,
    .resourceMask  = VK_SPIRV_RESOURCE_TYPE_UNIFORM_BUFFER_BIT_EXT,
    .source        = VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_CONSTANT_OFFSET_EXT,
    .sourceData    = {
           .constantOffset = {
               .heapArrayStride = static_cast<uint32_t>(buffer_descriptor_size)}}};

// Maps "layout (set = 1, binding = 0) uniform texture2D"
set_binding_mappings[1] = {
    .sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_AND_BINDING_MAPPING_EXT,
    .descriptorSet = 1,
    .firstBinding  = 0,
    .bindingCount  = 1,
    .resourceMask  = VK_SPIRV_RESOURCE_TYPE_SAMPLED_IMAGE_BIT_EXT,
    .source        = VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_CONSTANT_OFFSET_EXT,
    .sourceData    = {
           .constantOffset = {
               .heapOffset = static_cast<uint32_t>(image_heap_offset), .heapArrayStride = static_cast<uint32_t>(image_descriptor_size)}}};

// Maps "layout (set = 2, binding = 0) uniform sampler"
set_binding_mappings[2] = {
    .sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_AND_BINDING_MAPPING_EXT,
    .descriptorSet = 2,
    .firstBinding  = 0,
    .bindingCount  = 1,
    .resourceMask  = VK_SPIRV_RESOURCE_TYPE_SAMPLER_BIT_EXT,
    .source        = VK_DESCRIPTOR_MAPPING_SOURCE_HEAP_WITH_CONSTANT_OFFSET_EXT,
    .sourceData    = {
           .constantOffset = {
               .heapOffset = static_cast<uint32_t>(sampler_heap_offset), .heapArrayStride = static_cast<uint32_t>(sampler_descriptor_size)}}};
----

These mappings need to be passed to the corresponding shader stages:

[,cpp]
----
VkShaderDescriptorSetAndBindingMappingInfoEXT descriptor_set_binding_mapping_info{
    .sType        = VK_STRUCTURE_TYPE_SHADER_DESCRIPTOR_SET_AND_BINDING_MAPPING_INFO_EXT,
    .mappingCount = static_cast<uint32_t>(set_binding_mappings.size()),
    .pMappings    = set_binding_mappings.data()};

shader_stages[0].pNext = &descriptor_set_binding_mapping_info;
shader_stages[1].pNext = &descriptor_set_binding_mapping_info;
----

=== Untyped pointers

**Note:** This is not yet demonstrated in this sample. Support also varies between shading languages and might not be available everywhere.

As a more forward-looking approach, descriptors can be accessed directly from a shader using SPIR-V untyped pointers, which are exposed in Vulkan via link:https://docs.vulkan.org/refpages/latest/refpages/source/VK_KHR_shader_untyped_pointers.html[VK_KHR_shader_untyped_pointers].

This requires shaders to be adapted accordingly and also requires the shading language to support this feature. In GLSL, for example, this is provided via link:https://github.com/KhronosGroup/GLSL/blob/main/extensions/ext/GLSL_EXT_descriptor_heap.txt[GLSL_EXT_descriptor_heap]:

[,glsl]
----
#extension GL_EXT_descriptor_heap: require
...
layout(descriptor_heap) uniform texture2D textureImage[];
layout(descriptor_heap) uniform sampler textureSampler[];
...
vec4 color = texture(sampler2D(textureImage[someIndex]));
----

== Links

* https://docs.vulkan.org/features/latest/features/proposals/VK_EXT_descriptor_heap.html[Extension proposal]
* https://docs.vulkan.org/guide/latest/descriptor_heap.html[Vulkan Guide entry]
* https://www.khronos.org/blog/vulkan-introduces-roadmap-2026-and-new-descriptor-heap-extension[Blog entry]
* https://vulkan.gpuinfo.org/displayextensiondetail.php?extension=VK_EXT_descriptor_heap[Extension device coverage]


