////
- Copyright (c) 2020-2024, Arm Limited and Contributors
-
- SPDX-License-Identifier: Apache-2.0
-
- Licensed under the Apache License, Version 2.0 the "License";
- you may not use this file except in compliance with the License.
- You may obtain a copy of the License at
-
-     http://www.apache.org/licenses/LICENSE-2.0
-
- Unless required by applicable law or agreed to in writing, software
- distributed under the License is distributed on an "AS IS" BASIS,
- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
- See the License for the specific language governing permissions and
- limitations under the License.
-
////
= Samples overview
:pp: {plus}{plus}
:toc:
:toclevels: 1
:doctype: book

== Introduction

This readme lists all Vulkan samples currently available in this repository.
They are grouped into multiple categories.
Many samples come with a tutorial, which can be found in their respective folders.

== Performance samples

The goal of these samples is to demonstrate how to use certain features and functions to achieve optimal performance.
To visualize this, they also include real-time profiling information.

=== xref:./performance/afbc/README.adoc[AFBC]

AFBC (Arm Frame Buffer Compression) is a real-time lossless compression algorithm found in Arm Mali GPUs, designed to tackle the ever-growing demand for higher resolution graphics.
This format is applied to the framebuffers that are to be written to the GPU.
This technology can offer bandwidth reductions of https://developer.arm.com/technologies/graphics-technologies/arm-frame-buffer-compression[up to 50%].

=== xref:./performance/command_buffer_usage/README.adoc[Command buffer usage]

This sample demonstrates how to use and manage secondary command buffers, and how to record them concurrently.
Implementing multi-threaded recording of draw calls can help reduce CPU frame time.

=== xref:./performance/constant_data/README.adoc[Constant data]

The Vulkan API exposes a few different ways in which we can send uniform data into our shaders.
There are enough methods that it raises the question "Which one is fastest?", and more often than not the answer is "It depends".
The main issue for developers is that the fastest methods may differ between the various vendors, so often there is no "one size fits all" solution.
This sample aims to highlight this issue, and help move the Vulkan ecosystem to a point where we are better equipped to solve this for developers.
This is done by having an interactive way to toggle different constant data methods that the Vulkan API expose to us.
This can then be run on a platform of the developers choice to see the performance implications that each of them bring.

=== xref:./performance/descriptor_management/README.adoc[Descriptor management]
An application using Vulkan will have to implement a system to manage descriptor pools and sets.
The most straightforward and flexible approach is to re-create them for each frame, but doing so might be very inefficient, especially on mobile platforms.
The problem of descriptor management is intertwined with that of buffer management, that is choosing how to pack data in `VkBuffer` objects.
This sample will explore a few options to improve both descriptor and buffer management.

=== xref:./performance/hpp_swapchain_images/README.adoc[HPP Swapchain images]

A transcoded version of the Performance sample <<swapchain_images,Swapchain images>> that illustrates the usage of the C{pp} bindings of vulkan provided by vulkan.hpp.

=== xref:./performance/layout_transitions/README.adoc[Layout transitions]

Vulkan requires the application to manage image layouts, so that all render pass attachments are in the correct layout when the render pass begins.
This is usually done using pipeline barriers or the `initialLayout` and `finalLayout` parameters of the render pass.
If the rendering pipeline is complex, transitioning each image to its correct layout is not trivial, as it requires some sort of state tracking.
If previous image contents are not needed, there is an easy way out, that is setting `oldLayout`/`initialLayout` to `VK_IMAGE_LAYOUT_UNDEFINED`.
While this is functionally correct, it can have performance implications as it may prevent the GPU from performing some optimizations.
This sample will cover an example of such optimizations and how to avoid the performance overhead from using sub-optimal layouts.

=== xref:./performance/msaa/README.adoc[MSAA]

Aliasing is the result of under-sampling a signal.
In graphics this means computing the color of a pixel at a resolution that results in artifacts, commonly jaggies at model edges.
Multisample anti-aliasing (MSAA) is an efficient technique that reduces pixel sampling error.

=== xref:./performance/multithreading_render_passes/README.adoc[Multi-threaded recording with multiple render passes]

Ideally you render all stages of your frame in a single render pass.
However, in some cases different stages can't be performed in the same render pass.
This sample shows how multi-threading can help to boost performance when using multiple render passes to render a single frame.

=== xref:./performance/pipeline_barriers/README.adoc[Pipeline barriers]

Vulkan gives the application significant control over memory access for resources.
Pipeline barriers are particularly convenient for synchronizing memory accesses between render passes.
Having barriers is required whenever there is a memory dependency - the application should not assume that render passes are executed in order.
However, having too many or too strict barriers can affect the application's performance.
This sample will cover how to set up pipeline barriers efficiently, with a focus on pipeline stages.

=== xref:./performance/pipeline_cache/README.adoc[Pipeline cache]

Vulkan gives applications the ability to save internal representation of a pipeline (graphics or compute) to enable recreating the same pipeline later.
This sample will look in detail at the implementation and performance implications of the pipeline creation, caching and management.

=== xref:./performance/render_passes/README.adoc[Render passes]

Vulkan render-passes use attachments to describe input and output render targets.
This sample shows how loading and storing attachments might affect performance on mobile.
During the creation of a render-pass, you can specify various color attachments and a depth-stencil attachment.
Each of those is described by a https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkAttachmentDescription.html[`VkAttachmentDescription`] struct, which contains attributes to specify the https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkAttachmentLoadOp.html[load operation] (`loadOp`) and the https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkAttachmentStoreOp.html[store operation] (`storeOp`).
This sample lets you choose between different combinations of these operations at runtime.

=== xref:./performance/specialization_constants/README.adoc[Specialization constants]

Vulkan exposes a number of methods for setting values within shader code during run-time, this includes UBOs and Specialization Constants.
This sample compares these two methods and the performance impact of them.

=== xref:./performance/subpasses/README.adoc[Sub passes]

Vulkan introduces the concept of _subpasses_ to subdivide a single xref:./performance/render_passes/README.adoc[render pass] into separate logical phases.
The benefit of using subpasses over multiple render passes is that a GPU is able to perform various optimizations.
Tile-based renderers, for example, can take advantage of tile memory, which being on chip is decisively faster than external memory, potentially saving a considerable amount of bandwidth.

=== xref:./performance/surface_rotation/README.adoc[Surface rotation]

Mobile devices can be rotated, therefore the logical orientation of the application window and the physical orientation of the display may not match.
Applications then need to be able to operate in two modes: portrait and landscape.
The difference between these two modes can be simplified to just a change in resolution.
However, some display subsystems always work on the "native" (or "physical") orientation of the display panel.
Since the device has been rotated, to achieve the desired effect the application output must also rotate.
In this sample we focus on the rotation step, and analyze the performance implications of implementing it correctly with Vulkan.

=== xref:./performance/swapchain_images/README.adoc[Swapchain images]

Vulkan gives the application some significant control over the number of swapchain images to be created.
This sample analyzes the available options and their performance implications.

=== xref:./performance/wait_idle/README.adoc[Wait idle]

This sample compares two methods for synchronizing between the CPU and GPU, `WaitIdle` and `Fences` demonstrating which one is the best option in order to avoid stalling.

=== xref:./performance/16bit_storage_input_output/README.adoc[16-bit storage InputOutput]

This sample compares bandwidth consumption when using FP32 varyings compared to using FP16 varyings with `VK_KHR_16bit_storage`.

=== xref:./performance/16bit_arithmetic/README.adoc[16-bit arithmetic]

This sample compares arithmetic throughput for 32-bit arithmetic operations and 16-bit arithmetic.
The sample also shows how to enable 16-bit storage for SSBOs and push constants.

=== xref:./performance/async_compute/README.adoc[Async compute]

This sample demonstrates using multiple Vulkan queues to get better hardware utilization with compute post-processing workloads.

=== xref:./performance/texture_compression_basisu/README.adoc[Basis Universal supercompressed GPU textures]

This sample demonstrates how to use Basis universal supercompressed GPU textures in a Vulkan application.

=== xref:./performance/multi_draw_indirect/README.adoc[GPU Rendering and Multi-Draw Indirect]

This sample demonstrates how to reduce CPU usage by offloading draw call generation and frustum culling to the GPU.

=== xref:./performance/texture_compression_comparison/README.adoc[Texture compression comparison]

This sample demonstrates how to use different types of compressed GPU textures in a Vulkan application, and shows  the timing benefits of each.

== API samples

The goal of these samples is to demonstrate how to use a given Vulkan feature at the API level with as little abstraction as possible.

=== xref:./api/compute_nbody/README.adoc[Compute shader N-Body simulation]

Compute shader example that uses two passes and shared compute shader memory for simulating a N-Body particle system.

=== xref:./api/dynamic_uniform_buffers/README.adoc[Dynamic Uniform buffers]

Dynamic uniform buffers are used for rendering multiple objects with separate matrices stored in a single uniform buffer object, that are addressed dynamically.

=== xref:./api/hdr/README.adoc[High dynamic range]

Implements a high dynamic range rendering pipeline using 16/32 bit floating point precision for all calculations.

=== xref:./api/hello_triangle/README.adoc[Hello Triangle]

A self-contained (minimal use of framework) sample that illustrates the rendering of a triangle.

=== xref:./api/hpp_compute_nbody/README.adoc[HPP Compute shader N-Body simulation]

A transcoded version of the API sample <<compute_nbody,Compute N-Body>> that illustrates the usage of the C{pp} bindings of Vulkan provided by vulkan.hpp.

=== xref:./api/hpp_dynamic_uniform_buffers/README.adoc[HPP Dynamic Uniform Buffers]

A transcoded version of the API sample <<dynamic_uniform_buffers,Dynamic Uniform buffers>> that illustrates the usage of the C{pp} bindings of Vulkan provided by vulkan.hpp.

=== xref:./api/hpp_hdr/README.adoc[HPP High dynamic range]

A transcoded version of the API sample <<hdr,High dynamic range>>that illustrates the usage of the C{pp} bindings of Vulkan provided by vulkan.hpp.

=== xref:./api/hpp_hello_triangle/README.adoc[HPP Hello Triangle]

A transcoded version of the API sample <<hello_triangle,Hello Triangle>> that illustrates the usage of the C{pp} bindings of Vulkan provided by vulkan.hpp.

=== xref:./api/hpp_hlsl_shaders/README.adoc[HPP HLSL shaders]

A transcoded version of the API sample <<hlsl_shaders,HLSL Shaders>> that illustrates the usage of the C{pp} bindings of Vulkan provided by vulkan.hpp.

=== xref:./api/hpp_instancing/README.adoc[HPP Instancing]

A transcoded version of the API sample <<instancing,Instancing>> that illustrates the usage of the C{pp} bindings of Vulkan provided by vulkan.hpp.

=== xref:./api/hpp_oit_linked_lists/README.adoc[HPP OIT Linked Lists]

A transcoded version of the API sample <<oit_linked_lists,OIT Linked Lists>> that illustrates the usage of the C{pp} bindings of Vulkan provided by vulkan.hpp.

=== xref:./api/hpp_separate_image_sampler/README.adoc[HPP Separate image sampler]

A transcoded version of the API sample <<separate_image_sampler,Separate image sampler>> that illustrates the usage of the C{pp} bindings of vulkan provided by vulkan.hpp.

=== xref:./api/hpp_terrain_tessellation/README.adoc[HPP Terrain Tessellation]

A transcoded version of the API sample <<terrain_tessellation,Terrain Tessellation>> that illustrates the usage of the C{pp} bindings of vulkan provided by vulkan.hpp.

=== xref:./api/hpp_texture_loading/README.adoc[HPP Texture Loading]

A transcoded version of the API sample <<texture_loading,Texture loading>> that illustrates the usage of the C{pp} bindings of vulkan provided by vulkan.hpp.

=== xref:./api/hpp_texture_mipmap_generation/README.adoc[HPP Texture run-time mip-map generation]

A transcoded version of the API sample <<texture_mipmap_generation,Texture run-time mip-map generation>> that illustrates the usage of the C{pp} bindings of vulkan provided by vulkan.hpp.

=== xref:./api/hpp_timestamp_queries/README.adoc[HPP Timestamp queries]

A transcoded version of the API sample <<timestamp_queries,Timestamp queries>> that illustrates the usage of the C{pp} bindings of vulkan provided by vulkan.hpp.

=== xref:./api/instancing/README.adoc[Instancing]

Uses the instancing feature for rendering many instances of the same mesh from a single vertex buffer with variable parameters and textures.

=== xref:./api/separate_image_sampler/README.adoc[Separate image sampler]

Separate image and samplers, both in the application and the shaders.
The sample demonstrates how to use different samplers for the same image without the need to recreate descriptors.

=== xref:./api/terrain_tessellation/README.adoc[Terrain Tessellation]

Uses a tessellation shader for rendering a terrain with dynamic level-of-detail and frustum culling.

=== xref:./api/texture_loading/README.adoc[Texture loading]

Loading and rendering of a 2D texture map from a file.

=== xref:./api/texture_mipmap_generation/README.adoc[Texture run-time mip-map generation]

Generates a complete mip-chain for a texture at runtime instead of loading it from a file.

=== xref:./api/hlsl_shaders/README.adoc[HLSL shaders]

Converts High Level Shading Language (HLSL) shaders to Vulkan-compatible SPIR-V.

=== xref:./api/timestamp_queries/README.adoc[Timestamp queries]

Using timestamp queries for profiling GPU workloads.

=== xref:./api/swapchain_recreation/README.adoc[Swapchain recreation]

A sample that implements best practices in handling swapchain recreation, for example due to window resizing or present mode changes.

=== xref:./api/oit_linked_lists/README.adoc[Order-independent transparency with per-pixel ordered linked lists]

A sample that implements an order-independent transparency algorithm using per-pixel ordered linked lists.

[[extension-samples]]
include::./extensions/README.adoc[]

== Tooling Samples

The goal of these samples is to demonstrate usage of tooling functions and libraries that are not directly part of the api.

=== xref:./tooling/profiles/README.adoc[Profiles Library]

Use the https://github.com/KhronosGroup/Vulkan-Profiles[Vulkan Profiles library] to simplify instance and device setup.
The library defines a common baseline of features, extensions, etc.

== General Samples

The goal of these samples is to demonstrate different techniques or showcase complex scenarios that doesn't necessarily fit any of the main categories.

=== xref:./general/mobile_nerf/README.adoc[Mobile NeRF]

A Neural Radiance Field synthesizer sample, based on textured polygons.