== Description

Please include a summary of the change, new sample or fixed issue.
Please also include relevant motivation and context.
Please read the https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.adoc[contribution guidelines]

Fixes #+++<issue number="">++++++</issue>+++

== General Checklist:

Please ensure the following points are checked:

* [ ] My code follows the https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.adoc#Code-Style[coding style]
* [ ] I have reviewed file https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.adoc#Copyright-Notice-and-License-Template[licenses]
* [ ] I have commented any added functions (in line with Doxygen)
* [ ] I have commented any code that could be hard to understand
* [ ] My changes do not add any new compiler warnings
* [ ] My changes do not add any new validation layer errors or warnings
* [ ] I have used existing framework/helper functions where possible
* [ ] My changes do not add any regressions
* [ ] I have tested every sample to ensure everything runs correctly
* [ ] This PR describes the scope and expected impact of the changes I am making

NOTE: The Samples CI runs a number of checks including:

* [ ] I have updated the header Copyright to reflect the current year (CI build will fail if Copyright is out of date)
* [ ] My changes build on Windows, Linux, macOS and Android.
Otherwise I have https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.adoc#General-Requirements[documented any exceptions]

== Sample Checklist

If your PR contains a new or modified sample, these further checks must be carried out _in addition_ to the General Checklist:

* [ ] I have tested the sample on at least one compliant Vulkan implementation
* [ ] If the sample is vendor-specific, I have https://github.com/KhronosGroup/Vulkan-Samples/tree/master/CONTRIBUTING.adoc#General-Requirements[tagged it appropriately]
* [ ] I have stated on what implementation the sample has been tested so that others can test on different implementations and platforms
* [ ] Any dependent assets have been merged and published in downstream modules
* [ ] For new samples, I have added a paragraph with a summary to the appropriate chapter in the xref:./../samples/README.adoc[samples readme]
* [ ] For new samples, I have added a tutorial README.adoc file to guide users through what they need to know to implement code using this feature.
For example, see link:./../samples/extensions/conditional_rendering[conditional_rendering]
